### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ShotzVFX** [AN3Orik/PowerIK-UE5#1]
hi i dont know if there is other way to ask but u have this working on 5.4? cuz i cant compile it says rebuild from source but even that i try to compile all project but still the same

**Comment by AN3Orik** [comment]
Can you provide some screens with error to be more clear?

**Comment by AN3Orik** [comment]
I've uploaded built binaries for UE 5.4.1 into repository. Check it out.

**Comment by ShotzVFX** [comment]
wow thank you very much u save me it works!!  thank u again i should remove the not working thread? im newbi here dont know if that looks bad i remove it if u want
